services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ss123!
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ss123!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
